<html>
    <head>
        <meta charset="utf-8"/>
        <title>Eintopf PHP example</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <style>
            body {
                margin: 50px 0 0 0;
                padding: 0;
                width: 100%;
                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
                text-align: center;
                color: rgba(144, 144, 144, 1.0)
            }
            h1 {
                color: #719e40;
                font-weight: 200;
            }
            h2 {
                font-weight: 200;
               }
        </style>
    </head>
    <body>
        <h1>Eintopf PHP Example</h1>
        <div>Welcome to Slim - a microframework for PHP</div>

        <?php if (isset($name)) : ?>
            <h2>Hello <?= htmlspecialchars($name); ?>!</h2>
        <?php else: ?>
            <p>Try <a href="/Eintopf">/Eintopf</a></p>
        <?php endif; ?>
    </body>
</html>
